# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herald', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentnotification',
            name='attachments',
            field=models.TextField(null=True),
        ),
    ]
