# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herald', '0002_auto_20161017_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_class',
            field=models.CharField(max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='sentnotification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Success'), (2, 'Failed'), (3, 'User Disabled')], default=0),
        ),
    ]
