# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herald', '0002_sentnotification_attachments'),
        ('herald', '0004_notification_verbose_name'),
    ]

    operations = [
    ]
